# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-01 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_station', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stations',
            name='station_type',
            field=models.CharField(default='petrol', max_length=10),
        ),
    ]
